### ISSUE TITLE
Does not work for vcsh or fake bare git technique

### ISSUE THREAD

**Issue by DancingQuanta** [chemzqm/vim-easygit#5]
I am using [vcsh](https://github.com/RichiH/vcsh) which allows me to version control my dotfiles with git.
`vcsh` works by (taking a line from its manpage)

> vcsh  is  using  a  technique called fake bare Git repositories, keeping $GIT_DIR in a different directory from $GIT_WORK_TREE which is pointed to $HOME.

So if I want to commit a change for a vcsh repo, I enter a vcsh environment then which have a different `$GIT_DIR` compared to `$GIT_WORK_TREE` for that repo.

If I tried to execute `:Gcommit .` in a file I get the error `Git directory not found`.
I looked through the source code and learnt that `vim-easygit` searchs for a `.git`.
Unfortunately fake bare technique puts the repo elsewhere.

To support fake bare repo, you may need to read from $GIT_DIR or execute a git command to check it's output to see if it is in a repo or not.

**Comment by chemzqm** [comment]
Thanks, I will take your advise

**Comment by chemzqm** [comment]
Fixed, easygit will use `$GIT_DIR` at first and then use `git rev-parse --show-toplevel` to get the root directory, for people want to speed up, they can disable the `rev-parse` system command by `let g:easygit_enable_root_rev_parse = 0`
